dalmo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('moments', views.all_moments, name="all_moments"),
    path('entries', views.all_entries, name="all_entries"),
]

main/models.py
from datetime import date, time
from types import LambdaType
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.utils import timezone

date_format = '%Y-%m-%d' # Used by multiple methods to define format passed in views
def make_aware_date(str_date, format = date_format):
    """Create timezone aware dates from strings"""
    date = timezone.datetime.strptime(str_date, format)
    return date

# Extend from default user model.
class User(AbstractUser):
    pass

    def __str__(self):
        return self.username

class Moment(models.Model):
    feeling = models.CharField(max_length=50)
    cause = models.CharField(max_length=300)
    date_added = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='moments')

    def save(self, *args, **kwargs):
        """Overriding default save method to save date and time instance is created."""
        if not self.id:
            self.date_added = self.date_added if self.date_added else timezone.localtime()
            self.feeling = self.feeling.lower()
        return super(Moment, self).save(*args, *kwargs)

    def __str__(self):
        return f"Moment {self.id}: {self.feeling}"

    @property
    def count_feeling(self):
        """Returns number of moments with the same feeling as instance"""
        cls = Moment
        return cls.objects.filter(feeling = self.feeling).count()

    @classmethod
    def list_moments(cls, from_date=None, to_date=None, search_term=""):
        """Return queryset of all moments within a given date range that match a given search term. By default, it will retain all Moment instances."""
        moments = cls.search_moments(search_term).order_by("date_added")
        earliest, latest = moments.first(), moments.last()
        from_date = make_aware_date(from_date) if from_date is not None else earliest.date_added
        print(f"FROM DATE: {from_date}")
        to_date = make_aware_date(to_date) if to_date is not None else latest.date_added
        return moments.filter(date_added__date__range = [from_date, to_date]).order_by("-date_added")

    @classmethod
    def by_date(cls, from_date=None, to_date=None, search_term=""):
        """Return dictionary of moments sorted by date within date range. If no range is provided, it will return a sorted list of all moments."""
        moments = cls.list_moments(from_date, to_date, search_term)
        print(moments)
        dates = [d for d in { m.date_added.date() for m in moments }]
        dated_moments = [{"date":d, "moments":moments.filter(date_added__date=d).order_by("-date_added")} for d in dates]
        dated_moments.sort(key=lambda m: m['date'], reverse=True)
        return dated_moments

    @classmethod
    def count_emotions(cls, from_date=None, to_date=None):
        """Return how many times each emotion is saved"""
        moments = list(cls.list_moments(from_date, to_date)) 
        feeling_counts = [dict(feeling_count) for feeling_count in {tuple(feeling.items()) for feeling in [{"emotion":moment.feeling, "count":moment.count_feeling} for moment in moments]}]
        return sorted(feeling_counts, key=lambda e: e['count'], reverse=True)

    @classmethod
    def search_moments(cls, search_term=""):
        """Return queryset of moments by searching for feelings and causes"""
        return cls.objects.filter(feeling__icontains = search_term).order_by('-date_added')

class Entry(models.Model):
    class DayRating(models.IntegerChoices):
        """Integer choices for daily datings"""
        VERY_GOOD = 5, ('really good')
        GOOD = 4, ('good')
        NEUTRAL = 3, ('neutral')
        BAD = 2, ('bad')
        VERY_BAD = 1, ('really bad')

    class TidinessRating(models.IntegerChoices):
        """Integer choices for tidiness datings"""
        VERY_TIDY = 5, ('really tidy')
        TIDY = 4, ('tidy')
        NEUTRAL = 3, ('neutral')
        UNTIDY = 2, ('untidy')
        VERY_UNTIDY = 1, ('really untidy')

    rating = models.PositiveIntegerField(choices=DayRating.choices)
    sleep_time = models.DateTimeField()
    wake_time = models.DateTimeField()
    meals_amount = models.PositiveIntegerField()
    snacks = models.BooleanField(default=False)
    water_amount = models.PositiveIntegerField()
    tidiness_rating = models.PositiveIntegerField(choices=TidinessRating.choices)
    date_added = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entries')

    class Meta:
        verbose_name_plural = 'Entries'

    def save(self, *args, **kwargs):
        """Overriding default save method to save date and time instance is created."""
        if not self.id:
            self.date_added = timezone.localtime() - timezone.timedelta(days=7)
        return super(Entry, self).save(*args, *kwargs)

    def __str__(self):
        return f"Entry {self.id}: {self.date_added.strftime('%d %b %Y')}"

    @property
    def moments_from_this_day(self):
        """Returns all Moment instances from the same date as Entry instance."""
        moments = Moment.objects.filter(date_added__date = self.date_added.date()).all()
        return moments

    @property
    def sleep_duration(self):
        """Calculates sleep duration based on sleep and wake up times and returns value in seconds"""
        sleep_duration = self.wake_time - self.sleep_time
        return sleep_duration.seconds

    @classmethod
    def list_entries(cls, from_date=None, to_date=None):
        """Return list of entries within a given date range"""
        # from_date = timezone.datetime.strptime(from_date, date_format)
        # to_date = timezone.datetime.strptime(to_date, date_format)
        # entries = cls.objects.filter(
        #     date_added__date__gte=from_date.date(),
        #     date_added__date__lte=to_date.date()).all()
        # return entries

        entries = cls.objects.all().order_by("date_added")
        earliest, latest = entries.first(), entries.last()
        from_date = make_aware_date(from_date) if from_date is not None else earliest.date_added
        to_date = make_aware_date(to_date) if to_date is not None else latest.date_added
        return entries.filter(date_added__date__range=[from_date, to_date]).order_by("-date_added")

    @classmethod
    def average_rating(cls, from_date=None, to_date=None):
        """Return average daily rating of entries in date range"""
        entries = cls.list_entries(from_date, to_date)
        if entries:
            average_rating = sum([entry.rating for entry in entries]) / len(entries)
            return cls.DayRating(round(average_rating))

    @classmethod
    def average_sleep_duration(cls, from_date=None, to_date=None):
        """Return average sleep duration of entries in date range"""
        entries = cls.list_entries(from_date, to_date)
        if entries:
            return round(sum([e.sleep_duration for e in entries]) / len(entries))

    @classmethod
    def average_meals_amount(cls, from_date=None, to_date=None):
        """Return average number of meals had per day in given time period"""
        entries = cls.list_entries(from_date, to_date)
        if entries:
            return round(sum([e.meals_amount for e in entries]) / len(entries))

    @classmethod
    def average_water_amount(cls, from_date=None, to_date=None):
        """Return average number of water glasses had per day in given time period"""
        entries = cls.list_entries(from_date, to_date)
        if entries:
            return round(sum([e.water_amount for e in entries]) / len(entries))

    @classmethod
    def average_tidiness_rating(cls, from_date=None, to_date=None):
        """Return average tidiness rating of entries in date range"""
        entries = cls.list_entries(from_date, to_date)
        if entries:
            average_tidiness = sum([entry.tidiness_rating for entry in entries]) / len(entries)
            return cls.DayRating(round(average_tidiness))

main/forms.py
from django import forms

class DateForm(forms.Form):
    from_date = forms.DateInput(label="from date")
    to_date = forms.DateInput(label="to date")

main/views.py
from datetime import tzinfo
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone

from main.models import Entry, Moment

today = timezone.localtime()
week_ago = today - timezone.timedelta(days=7)

def index(request):
    from_date = None
    to_date = None

    if request.GET:
        from_date = request.GET['from-date'] if len(request.GET['from-date']) > 0 else None
        to_date = request.GET['to-date'] if len(request.GET['to-date']) > 0 else None

    print(f"FROM_DATE 1: {from_date}")

    moments = Moment.list_moments(from_date=from_date, to_date=to_date)
    entries = Entry.list_entries(from_date=from_date, to_date=to_date)
    ctx = { 
        "title": "Know Yourself",
        "from_date": from_date,
        "to_date": to_date,
        "moments_number": len(moments),
        "emotions": Moment.count_emotions(from_date=from_date, to_date=to_date),
        "check_entry": Entry.list_entries(from_date=from_date, to_date=to_date),
        "entries_amount": len(entries),
        "average_rating": Entry.average_rating(from_date=from_date, to_date=to_date),
        "sleep_duration": Entry.average_sleep_duration(from_date=from_date, to_date=to_date),
        "average_meals": Entry.average_meals_amount(from_date=from_date, to_date=to_date),
        "average_water": Entry.average_water_amount(from_date=from_date, to_date=to_date),
        "average_tidiness": Entry.average_tidiness_rating(from_date=from_date, to_date=to_date)
        }

    return render(request, 'main/index.html', ctx)

def all_moments(request):
    if request.GET:
        from_date = request.GET['from-date'] if len(request.GET['from-date']) > 0 else None
        to_date = request.GET['to-date'] if len(request.GET['to-date']) > 0 else None
        search_term = request.GET['search']
    else:
        from_date = None
        to_date = None
        search_term = ""

    moments_by_date = Moment.by_date(from_date, to_date, search_term)

    ctx = { 
        "title": "Entries",
        "from_date": from_date,
        "to_date": to_date,
        "moments_by_date": moments_by_date,
        "search_term": search_term
        }
    return render(request, 'main/all_moments.html', ctx)

def all_entries(request):
    ctx = {}
    return render(request, "main/all_entries.html", ctx)

main/templates/main/add_button.html
{% load static %}

<button id="addButton">
    <img src="{% static 'images/plus_icon.svg' %}" alt="plus">
</button>

<div class="container" id="addOverlay">
    <a href="">
    <button class="btn btn-light-pink"><span class="iconify mr-2" data-icon="ion:journal-outline" data-height="14"></span> Today's Entry</button>
    </a>
    <a href="">
    <button class="btn btn-purple"><span class="iconify mr-2" data-icon="el:time" data-height="14"></span> Moment</button>
    </a>
</div>

main/templates/main/all_entries.html
{% extends 'main/base.html' %}

{% block body %}
<div class="container">
    <div class="rounded-card text-purple text-center title-2">Daily Entries</div>
    {% include 'main/date_selector.html' with variant=3 %}
</div>
{% endblock body %}

main/templates/main/all_moments.html
{% extends 'main/base.html' %}

{% block body %}
<div class="container">
    <div class="rounded-card text-purple text-center title-2">Moments</div>
    {% include 'main/date_selector.html' with variant=2 %}
</div>

{% for date in moments_by_date %}
<div class="container">
    {% if date.moments %}
    <h2 class="heading-2 my-3">{{ date.date }}</h2>
    {% endif %}
    <table class="w-100">
        {% for moment in date.moments  %}
            <tr>
                <td>
                    <a href="">
                        <div class="w-100">
                        <span class="text-purple mr-2">{{ moment.feeling|lower }}</span>
                        <span class="text-light-gray-2">because {{ moment.cause|truncatewords:3 }}</span>
                        </div>
                    </a>
                </td>
                <td class="text-right">{{ moment.date_added|time }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% empty %}
<div class="container heading-2">No moments</div>
{% endfor %}

{% endblock body %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    {% if title %}
    <title>Dalmo - {{ title }}</title>
    {% else %}
    <title>Dalmo - Know Yourself</title>
    {% endif %}

    {% block styles %}{% endblock styles %}
</head>
<body>

{% include 'main/navbar.html' %}

{% block body %}
{% endblock body %}

{% include 'main/add_button.html' %}
{% include 'main/footer.html' %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://code.iconify.design/2/2.0.3/iconify.min.js"></script>
<script src="{% static 'js/addButton.js' %}"></script>
{% endblock scripts %}
</body>
</html>

main/templates/main/date_selector.html
<div class="mb-5">
  <div class="heading-2 text-dark-purple mb-3">Select a Date Range</div>
  <form method='GET'>
    <div class="d-flex justify-content-between">
      <div>
        <label for="from-date"class="text-dark-purple   mr-2  flex-fill">from</label>
        <input name="from-date" id="from-date" type="date" value={{ from_date }}>
      </div>
      <div>
        <label for="to-date" class="text-dark-purple mr-2">to</label>
        <input name="to-date" id="to-date" type="date" value={{ to_date }}>
      </div>
    </div>

    {% if variant == 2 %}
    <div class="mt-2 d-flex align-items-center">
      <label for="search" class="text-dark-purple m-0 mr-3"><span class="iconify" data-icon="fe:search" data-width="18"></span></label>
      <input name="search" id="search" type="text" class="flex-fill" placeholder="Search for feelings or causes" value="{{ search_term }}">
    </div>
    {% endif %}

    {% if variant == 3 %}
    <div class="mt-2 d-flex">
      <label for="sort" class="text-dark-purple mr-2">sort by</label>
      <select class="flex-fill" name="sort" id="sort">
        <option value="date-asc">Date (ascending)</option>
        <option value="date-desc">Date (descending)</option>
      </select>
    </div>
    {% endif %}

    <button class="btn-compact btn-purple w-100">Submit</button>
  </form>
</div>

main/templates/main/footer.html
<footer>
    <p>© 2021 Victor Maina </p>
</footer>
<div></div>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load duration %}

{% block body %}

<div class="container">
  <div class="rounded-card">
    <h1 class="title-2 text-purple mb-1">Good morning <span class="iconify ml-3" data-icon="fa-solid:sun"></span></h1>
    <p>Remember to make an entry today.</p>
  </div>

  {% include 'main/date_selector.html' with variant=1 %}

  {% comment %} MOMENT SECTION {% endcomment %}
  <section class="mb-5">
    <div class="d-flex align-items-center justify-content-between mb-3">
      <h1 class="title-2">Moments</h1>
      <div class="heading-2">{{ moments_number }} moment{{ moments_number|pluralize }}</div>
    </div>
    <p class="mb-4">Emotions from recorded moments in selected daterange.</p>
    <div class="rounded-card">
      <ul class="p-0 m-0">

        {% for emotion in emotions %}
        <li class="d-flex py-2 align-items-center">
          <p class="m-0">{{ emotion.emotion }}</p>
          <hr>
          <p class="m-0 font-weight-bold text-dark-purple">{{ emotion.count }}</p>
        </li>
        {% empty %}
        <li class="d-flex py-2 align-items-center">No emotions</li>
        {% endfor %}
      </ul>
    </div>
    <a href="{% url 'main:all_moments' %}"><button class="btn btn-purple">View Moments <span class="iconify" data-icon="fluent:arrow-right-16-filled" data-height="16"></span></button></a>
  </section>

  {% comment %} ENTRY SECTION {% endcomment %}
  <section class="mb-5">
    <div class="d-flex align-items-center justify-content-between mb-3">
      <h1 class="title-2">Entries</h1>
      {% comment %} Add if else statement here for plural {% endcomment %}
      <div class="heading-2">{{ entries_amount }} Entr{{ entries_amount|pluralize:'y,ies' }}</div>
    </div>
    <p class="mb-4">Calculated averages of all daily entries in the selected date range.</p>

    {% comment %} DYNAMIC AREA - Interpolate data here {% endcomment %}

    {% if check_entry %}    
    {% comment %} Average Rating {% endcomment %}
    <div class="text-dark-purple rounded-card">
      <h2 class="heading-2 mb-3">Average Rating</h2>
      <div class="d-flex align-items-center justify-content-between">
        <p class="mb-0">{{ average_rating.label|capfirst }}</p>
        {% include 'main/rated.html' with rating=average_rating.value %}
      </div>
    </div>

    {% comment %} Average Sleep {% endcomment %}
    <div class="text-dark-purple rounded-card d-flex justify-content-between align-items-center">
      <h2 class="heading-2"><span class="iconify mr-2" data-icon="akar-icons:moon" data-height="14"></span> Sleep Duration</h2>
      <p class="text-right">about {{ sleep_duration|duration }}</p>
    </div>

    {% comment %} Average Water Intake {% endcomment %}
    <div class="text-dark-purple rounded-card d-flex justify-content-between align-items-center">
      <h2 class="heading-2"><span class="iconify mr-2" data-icon="gg:glass-alt" data-height="14"></span> Water</h2>
      <p class="text-right">about {{ average_water }} glass{{ average_water|pluralize:"es" }}</p>
    </div>

    {% comment %} Average Food Intake {% endcomment %}
    <div class="text-dark-purple rounded-card d-flex justify-content-between align-items-center">
      <h2 class="heading-2"><span class="iconify mr-2" data-icon="fluent:food-24-filled" data-height="14"></span> Meals</h2>
      <p class="text-right">about {{ average_meals }} meal{{ average_water|pluralize }}</p>
    </div>

    {% comment %} Average Tidiness Rating {% endcomment %}
    <div class="text-dark-purple rounded-card">
      <h2 class="heading-2 mb-3">Tidiness Rating</h2>
      <div class="d-flex align-items-center justify-content-between">
        <p class="mb-0">{{ average_tidiness.label|capfirst }}</p>
        {% include 'main/rated.html' with rating=average_tidiness.value %}
      </div>
    </div>
    <a href="{% url 'main:all_entries' %}"><button class="btn btn-purple">View Entries <span class="iconify" data-icon="fluent:arrow-right-16-filled" data-height="16"></span></button></a>
    {% else %}
    <div class="rounded-card">No entries</div>
    {% endif %}
  </section>


</div>

{% endblock body %}

main/templates/main/navbar.html
{% load static %}
<nav class="navbar container">
  {% if request.path != '/' %}
  <a href="javascript:history.back()">
    <div><span class="iconify color-dark-purple" data-icon="akar-icons:arrow-left" data-width="18"></span></div>
  </a>
  {% endif %}

  <a class="navbar-brand p-0 m-0" href="{% url 'main:index' %}">
    <img src="{% static 'images/logo.svg' %}" alt="logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="iconify color-dark-purple" data-icon="dashicons:menu-alt" data-height="18"></span>
  </button>
  <div class="text-right px-3 collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="#">Dashboard <span class="iconify color-dark-purple ml-3" data-icon="akar-icons:home" data-width="15"></span>
      <a class="nav-item nav-link" href="#">Entries <span class="iconify color-dark-purple ml-3" data-icon="ion:journal-outline" data-width="15"></span></a>
      <a class="nav-item nav-link" href="#">Moments <span class="iconify color-dark-purple ml-3" data-icon="carbon:face-activated" data-width="15"></span></a>
    </div>
  </div>
</nav>
<div class="navbarPadding"></div>

main/templates/main/rated.html
<div class="rating d-flex">
    {% for circle in "x"|ljust:"5"  %}
        {% if forloop.counter <= rating %}
            <span class="iconify mx-1" data-icon="akar-icons:circle-fill" data-width="16"></span>
        {% else %}
            <span class="iconify mx-1" data-icon="akar-icons:circle" data-width="16"></span>
        {% endif %}
    {% endfor %}
</div>